In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [6]:
data = pd.read_csv("IRIS.csv")

In [7]:
data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [8]:
data.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [10]:
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [11]:
data['species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: species, dtype: int64

In [12]:
data.shape

(150, 5)

In [13]:
data.replace({"species": {"Iris-setosa": 1, "Iris-versicolor": 2, "Iris-virginica": 3}}, inplace=True)

In [14]:
data.head()


sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        1
1           4.9          3.0           1.4          0.2        1
2           4.7          3.2           1.3          0.2        1
3           4.6          3.1           1.5          0.2        1
4           5.0          3.6           1.4          0.2        1

In [15]:
x = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)


In [19]:
from sklearn.linear_model import LogisticRegression

model_1 = LogisticRegression()
model_1.fit(x_train, y_train)

LogisticRegression()

In [25]:
y_pred = model_1.predict(x_test)
y_pred

array([3, 2, 1, 3, 1, 3, 1, 2, 2, 2, 3, 2, 2, 2, 2, 1, 2, 2, 1, 1, 3, 2,
       1, 1, 3, 1, 1, 2, 2, 1], dtype=int64)

In [26]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


1.0

In [20]:
from sklearn.ensemble import RandomForestClassifier

model_2 = RandomForestClassifier()
model_2.fit(x_train, y_train)

RandomForestClassifier()

In [21]:
from sklearn.tree import DecisionTreeClassifier

model_3 = DecisionTreeClassifier()
model_3.fit(x_train, y_train)

DecisionTreeClassifier()

In [27]:
from sklearn.metrics import accuracy_score, f1_score

x_test_prediction_1 = model_1.predict(x_test)
accuracy_1 = accuracy_score(y_test, x_test_prediction_1)

x_test_prediction_2 = model_2.predict(x_test)
accuracy_2 = accuracy_score(y_test, x_test_prediction_2)

x_test_prediction_3 = model_3.predict(x_test)
accuracy_3 = accuracy_score(y_test, x_test_prediction_3)

In [28]:
print("LogisticRegression Model\nAccuracy Score: ", accuracy_1)
print()
print("RandomForestClassifier Model\nAccuracy Score: ", accuracy_2)
print()
print("DecisionTreeClassifier Model\nAccuracy Score: ", accuracy_3)

LogisticRegression Model
Accuracy Score:  1.0

RandomForestClassifier Model
Accuracy Score:  1.0

DecisionTreeClassifier Model
Accuracy Score:  1.0
